---
name: Kimi K2
version: 1.1.0
schema: v1
models:
  - name: Kimi K2.5
    provider: openrouter
    model: moonshotai/kimi-k2.5
    apiKey: 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
    defaultCompletionOptions:
      contextLength: 262144
    capabilities:
      - tool_use
    roles:
      - apply
      - chat
      - edit
